version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-front
    ports:
      - "8080:80"
    volumes:
      - .:/app

  backend:
    build:
      context: .
      dockerfile: Dockerfile-back
    volumes:
      - ./eventos.json:/data/eventos.json
    ports:
      - "3000:3000"